@extends('layouts.main')

@section('content')
    <div class="container-fluid p-0 pb-3">
        @include('partials.banner')

        <div class="container-fluid pt-4 wow fadeInUp" data-wow-delay="0.1s">
            <div class="container">
                
                <div class="row gy-5 gx-4">
                    <div class="col-lg-12 col-md-6">
                        <ul class="list-group">
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/11/Lampiran-I-Akademik-Kepdirjen-232-2019.pdf">Lampiran 1 Akademik Keputusan Direktur Jenderal Pembelajaran Dan Kemahasiswaan Kementerin Riset, Teknologi, Dan Pendidikan Tinggi Republik Indonesia Nomor 232/B/Hk/2019 Tentang Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-Kepdirjen-No.47-thn-2019-Pedoman.pdf">Lampiran Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 47/B/HK/2019 Tentang Pedoman Pengusulan dan Penyesuaian Nama Program Studi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Kepdirjen-No.47-thn-2019-ttg-Pedoman.pdf">Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 47/B/HK/2019 Tentang Pedoman Pengusulan dan Penyesuaian Nama Program Studi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Kepdirjen-No.46-thn-2019-ttg-Daftar-Nama-Program-Studi.pdf">Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-1-Akademik-1.pdf">Lampiran 1 Program Akademik Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-2-S2S3-Terapan.pdf"> 2 Program Magister Terapan dan Doktor Terapan Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-3-Profesi.pdf">Lampiran 3 Program Profesi Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-4-Spesialis.pdf">Lampiran 4 Program Spesialis Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-5-D3D4.pdf">Lampiran 5 Program Vokasi Diploma III dan Sarjana Terapan Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2019/03/Lampiran-6-D1D2.pdf">Lampiran 6 Vokasi Diploma I dan Diploma II Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 46/B/HK/2019 Tentang Daftar Nama Program Studi Pada Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://www.kopertis3.or.id/v6/wp-content/uploads/2018/05/SK-Dirjen-Belmawa-Tentang-Prosedur-Perubahan-Data-Mahasiswa.pdf">Surat Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 302 / B / SK / 2017 Tentang Prosedur Perubahan Data Mahasiswa</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/v2/wp-content/uploads/SK-DIRJEN-tentang-Pedoman-RPL-SALINAN.pdf">Surat Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 123 / B / SK / 2017 Tentang Pedoman Tata Cara Penyelenggaraan Rekognisi Pembelajaran Lampau</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/v2/wp-content/uploads/Lampiran-Pedoman-RPL-SALINAN.pdf">Lampiran Surat Keputusan Direktur Jenderal Pembelajaran dan Kemahasiswaan Kementerian Riset, Teknologi, dan Pendidikan Tinggi Republik Indonesia Nomor 123 / B / SK / 2017 Tentang Pedoman Tata Cara Penyelenggaraan Rekognisi Pembelajaran Lampau</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/html/wp-content/uploads/2011/04/Keputusan-Dirjen-Dikti-No-25-Tahun-20141.pdf">Surat Keputusan Direktur Jenderal Pendidikan Tinggi Nomor: 25 / DIKTI / Kep / 2014 Tanggal 30 Juni 2015 Tentang Panduan Umum Pengenlan Kehidupan Kampus Untuk Mahasiswa Baru</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/html/wp-content/uploads/2011/04/SKDirjen163-DIKTI-Kep-2007Lengkap.pdf">Surat Keputusan Direktur Jenderal Pendidikan Tinggi Nomor: 163 / DIKTI / KEP / 2007 tentang Penataan dan Kodifikasi Program Studi di Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/html/wp-content/uploads/2011/04/kepdirjen-034-2002.pdf">Surat Keputusan Direktur Jenderal Pendidikan Tinggi No: 34 / DIKTI / Kep / 2002 Tentang Perubahan dan Peraturan Direktur Jenderal Pendidikan Tinggi No: 08 / DIKTI / Kep / 2002 Tentang Penggunaan Teknis Keputusan Menteri Pendidikan Nasional No: 184 / U / 2001 Tentang Pedoman Pengawasan – Pengendalian dan Pembinaan Program Diploma, Sarjana dan Pascasarjana di Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/html/wp-content/uploads/2011/04/SKDirjen08-DIKTI-Kep-2002.docx">Surat Keputusan Direktur Jenderal Pendidikan Tinggi No: 08 / DIKTI / Kep / 2002 Tentang Penutupan Keputusan Menteri Pendidikan Nasional Nomor 184 / U / 2001 Tentang Pedoman Pengendalian Program Pengembalian dan Pembimbing Diploma, Sarjana dan Pasca Sarjana di Perguruan Tinggi</a></li>
                            <li class="list-group-item bg-light"><a class="text-dark" href="http://lldikti3.ristekdikti.go.id/html/wp-content/uploads/2011/04/108-dikti-kep-2001.pdf">Surat Keputusan Direktur Jenderal Pendidikan Tinggi Nomor: Nomor: 108 / DIKTI / Kep / 2001 Tentang Pedoman Pembukaan Program Studi dan / atau berdasarkan Keputusan Menteri Pendidikan Nasional Nomor: 234 / U / 2000 Tentang Pendirian Perguruan Tinggi</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


